# Generated by Django 4.2.16 on 2024-11-30 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_customuser_age_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('активно', 'Активно'), ('завершино', 'Завершино'), ('впроцессе', 'Впроцессе')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('активно', 'Активно'), ('завершино', 'Завершино'), ('впроцессе', 'Впроцессе')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('активно', 'Активно'), ('завершино', 'Завершино'), ('впроцессе', 'Впроцессе')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CharityCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=250)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('женщина', 'Женщина'), ('мужчина', 'Мужчина')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('валантер', 'Валантер'), ('Нуждающийся', 'Нуждающийся')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.AddField(
            model_name='applyhelp',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.category'),
        ),
        migrations.AddField(
            model_name='applyhelp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationcharity',
            name='company_charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.charitycompany'),
        ),
        migrations.AddField(
            model_name='applicationcharity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='applay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.applyhelp'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
